apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kellnr.fullname" . }}
  labels:
    {{- include "kellnr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
    {{- end}}
  selector:
    matchLabels:
      {{- include "kellnr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- /* These annotations trigger a rolling update when the config or secret changes */}}
        configHash: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- if not .Values.secret.existingSecret }}
        secretHash: {{ include (print $.Template.BasePath "/secret-config.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.docBuilder.enabled }}
        docConfigHash: {{ include (print $.Template.BasePath "/doc-config.yaml") . | sha256sum }}
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kellnr.selectorLabels" . | nindent 8 }}
    spec:
      {{- if or .Values.pvc.enabled .Values.importCert.enabled .Values.docBuilder.enabled }}
      volumes:
        {{- if .Values.pvc.enabled }}
        - name: {{ .Values.deployment.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.deployment.volumes.persistentVolumeClaim }}
        {{- end }}
        {{- if .Values.importCert.enabled }}
        - name: {{ .Values.importCert.volumeName | quote }}
          configMap:
            name: {{ .Values.importCert.configMapName | quote }}
        {{- end }}
        {{- if .Values.docBuilder.enabled }}
        - name: cargo-config
          configMap:
            name: {{ .Values.docBuilder.configMapName | quote }}
        {{- end }}
        - name: certs
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      {{- end }}
      {{- if .Values.dns.enabled }}
      dnsPolicy: {{ .Values.dns.dnsPolicy | quote }}
      dnsConfig:
        nameservers:
          {{- toYaml .Values.dns.dnsConfig.nameservers | nindent 12 }}
        searches:
          {{- toYaml .Values.dns.dnsConfig.searches | nindent 12 }}
      {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kellnr.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if eq .Values.kellnr.log.level "debug" }}
          - name: RUST_BACKTRACE
            value: "1"
          {{- end }}
          {{- if .Values.kellnr.postgres.enabled }}
          - name: KELLNR_POSTGRESQL__PWD
            valueFrom:
              secretKeyRef: {{ toYaml .Values.kellnr.postgres.pwdSecretRef | nindent 16 }}
          {{- end }}
          {{- if and .Values.kellnr.oauth2.enabled .Values.kellnr.oauth2.clientSecretRef.name }}
          - name: KELLNR_OAUTH2__CLIENT_SECRET
            valueFrom:
              secretKeyRef: {{ toYaml .Values.kellnr.oauth2.clientSecretRef | nindent 16 }}
          {{- end }}
          {{- if .Values.kellnr.registry.cookieSigningKeySecretRef.name }}
          - name: KELLNR_REGISTRY__COOKIE_SIGNING_KEY
            valueFrom:
              secretKeyRef: {{ toYaml .Values.kellnr.registry.cookieSigningKeySecretRef | nindent 16 }}
          {{- end }}
          {{- if and .Values.docBuilder.enabled .Values.docBuilder.tokenSecretRef.name }}
          - name: RUSTUP_TOOLCHAIN
            value: {{ .Values.docBuilder.rustupToolchain | quote }}
          - name: CARGO_REGISTRIES_{{ .Values.docBuilder.registryName | upper | replace "-" "_" }}_TOKEN
            valueFrom:
              secretKeyRef: {{ toYaml .Values.docBuilder.tokenSecretRef | nindent 16 }}
          {{- end }}
          {{- with .Values.extraEnvVars }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name | quote }}
            - secretRef:
                name: {{ .Values.secret.existingSecret | default .Values.secret.name | quote }}
            {{- with .Values.extraEnvVarsCM }}
            - configMapRef:
                name: {{ . | quote }}
            {{- end }}
            {{- with .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ . | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.api.port }}
              name: kellnr-api
              protocol: TCP
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: kellnr-api
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: kellnr-api
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: kellnr-api
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          {{- end }}
          {{- if or .Values.pvc.enabled .Values.importCert.enabled .Values.docBuilder.enabled }}
          volumeMounts:
            {{- if .Values.pvc.enabled }}
            - mountPath: {{ .Values.kellnr.registry.dataDir | quote }}
              name: {{ .Values.deployment.volumes.name }}
              readOnly: false
            {{- end }}
            {{- if .Values.importCert.enabled }}
            - name: {{ .Values.importCert.volumeName }}
              mountPath: "/usr/local/share/ca-certificates/"
              readOnly: true
            {{- end }}
            {{- if .Values.docBuilder.enabled }}
            - name: cargo-config
              mountPath: "/usr/local/cargo/config.toml"
              subPath: config.toml
              readOnly: true
            {{- end }}
            - mountPath: /etc/ssl/certs
              name: certs
            - mountPath: /tmp
              name: tmp
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
