{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | quote }}
type: Opaque
stringData:
{{- include "kellnr.secretEnvVars" . | nindent 2 }}
{{- end }}
